-- Organizations table
CREATE TABLE organizations (
    organization_id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    contact_email VARCHAR(255),
    logo_filename VARCHAR(255)
);

-- Inserting statement 
INSERT INTO organizations (name, description, contact_email, logo_filename)
VALUES
('BrightFuture Builders', 'A nonprofit focused on improving community infrastructure through sustainable construction projects.', 'info@brightfuturebuilders.org', 'brightfuture-logo.png'),
('GreenHarvest Growers', 'An urban farming collective promoting food sustainability and education in local neighborhoods.', 'contact@greenharvest.org', 'greenharvest-logo.png'),
('UnityServe Volunteers', 'A volunteer coordination group supporting local charities and service initiatives.', 'hello@unityserve.org', 'unityserve-logo.png');

-- Selecting statement from organization
SELECT * FROM organizations;

SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'organizations';

__ Changing email datatype from array to varc
ALTER TABLE organizations
ALTER COLUMN contact_email TYPE VARCHAR(255)
USING contact_email::VARCHAR(255);


SELECT column_name, data_type, udt_name
FROM information_schema.columns
WHERE table_name = 'organizations'
ORDER BY ordinal_position;

ALTER TABLE organizations
ALTER COLUMN logo_filename TYPE VARCHAR(255)
USING logo_filename::VARCHAR(255);

SELECT column_name, data_type, column_default
FROM information_schema.columns
WHERE table_name = 'organizations'
ORDER BY ordinal_position;

ALTER TABLE organizations
ALTER COLUMN organization_id
ADD GENERATED BY DEFAULT AS IDENTITY;

-- Service projects table
CREATE TABLE service_projects (
    project_id SERIAL PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(organization_id),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    location VARCHAR(255),
    date DATE NOT NULL
);


SELECT * FROM service_projects;

-- Insert into service project
INSERT INTO service_projects
    (organization_id, title, description, location, date)
VALUES
(1, 'Community School Renovation',
 'Renovation of classrooms and improvement of school facilities.',
 'Lagos', '2026-10-05'),

(1, 'Community Center Construction',
 'Construction of a safe community center for local residents.',
 'Ogun', '2026-10-12'),

(1, 'Rural Road Improvement',
 'Improvement of roads connecting local communities.',
 'Ogun', '2026-10-20'),

(1, 'Clean Water Facility',
 'Construction of a sustainable clean water facility.',
 'Oyo', '2026-11-03'),

(1, 'Community Housing Project',
 'Construction support for affordable community housing.',
 'Lagos', '2026-11-15'),

(2, 'Community Vegetable Garden',
 'Development of a vegetable garden for local residents.',
 'Lagos', '2026-10-08'),

(2, 'Urban Farming Workshop',
 'Teaching residents sustainable urban farming methods.',
 'Ogun', '2026-10-18'),

(2, 'School Garden Project',
 'Creating a learning garden for students.',
 'Oyo', '2026-10-28'),

(2, 'Food Sustainability Program',
 'Promoting sustainable food production in the community.',
 'Lagos', '2026-11-07'),

(2, 'Community Tree Planting',
 'Planting fruit and shade trees around community farms.',
 'Ogun', '2026-11-20'),

(3, 'Food Donation Drive',
 'Collecting and distributing food to families in need.',
 'Lagos', '2026-10-10'),

(3, 'Community Cleanup',
 'Organizing volunteers to clean public community spaces.',
 'Ogun', '2026-10-22'),

(3, 'Charity Support Program',
 'Coordinating volunteers to support local charitable organizations.',
 'Lagos', '2026-11-01'),

(3, 'Senior Community Outreach',
 'Organizing volunteers for community outreach activities.',
 'Oyo', '2026-11-12'),

(3, 'Holiday Donation Campaign',
 'Coordinating donations and volunteers for a seasonal community campaign.',
 'Ogun', '2026-11-25');


SELECT * FROM service_projects;

-- Categories table
CREATE TABLE categories (
    category_id SERIAL PRIMARY KEY,
    category_name VARCHAR(255) UNIQUE NOT NULL
);

INSERT INTO categories (category_name)
VALUES 	('Environmental'),
		('Food and Poverty Relief'),
		('Arts and Culture'),
		('Environmental');


-- Create junction table
CREATE TABLE project_categories (
    project_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,

    PRIMARY KEY (project_id, category_id),

    FOREIGN KEY (project_id)
        REFERENCES service_projects(project_id)
        ON DELETE CASCADE,

    FOREIGN KEY (category_id)
        REFERENCES categories(category_id)
        ON DELETE CASCADE
);

SELECT project_id, title
FROM service_projects
ORDER BY project_id;

DELETE FROM project_categories
WHERE category_id = 3;

DELETE FROM categories
WHERE category_id = 3;

UPDATE categories
SET category_id = 3
WHERE category_id = 4;


INSERT INTO project_categories (project_id, category_id)
VALUES
    -- Environmental
    (4, 1),   -- Clean Water Facility
    (6, 1),   -- Community Vegetable Garden
    (7, 1),   -- Urban Farming Workshop
    (8, 1),   -- School Garden Project
    (9, 1),   -- Food Sustainability Program
    (10, 1),  -- Community Tree Planting
    (12, 1),  -- Community Cleanup

    -- Food and Poverty Relief
    (9, 2),   -- Food Sustainability Program
    (11, 2),  -- Food Donation Drive
    (13, 2),  -- Charity Support Program
    (15, 2),  -- Holiday Donation Campaign

    -- Community Service
    (1, 3),   -- Community School Renovation
    (2, 3),   -- Community Center Construction
    (3, 3),   -- Rural Road Improvement
    (5, 3),   -- Community Housing Project
    (6, 3),   -- Community Vegetable Garden
    (8, 3),   -- School Garden Project
    (10, 3),  -- Community Tree Planting
    (12, 3),  -- Community Cleanup
    (13, 3),  -- Charity Support Program
    (14, 3),  -- Senior Community Outreach
    (15, 3);  -- Holiday Donation Campaign

SELECT * FROM categories
ORDER BY category_id;

-- checking relationship
SELECT
    pc.project_id,
    sp.title,
    pc.category_id,
    c.category_name
FROM project_categories pc
JOIN service_projects sp
    ON pc.project_id = sp.project_id
JOIN categories c
    ON pc.category_id = c.category_id
ORDER BY pc.project_id, pc.category_id;

SELECT * FROM project_categories;


SELECT * 
FROM categories;

-- Relationship btw two tables
INSERT INTO project_categories (project_id, category_id)
VALUES
    -- Environmental projects
    (4, 1),    -- Clean Water Facility
    (6, 1),    -- Community Vegetable Garden
    (7, 1),    -- Urban Farming Workshop
    (8, 1),    -- School Garden Project
    (9, 1),    -- Food Sustainability Program
    (10, 1),   -- Community Tree Planting
    (12, 1),   -- Community Cleanup

    -- Food and Poverty Relief projects
    (9, 2),    -- Food Sustainability Program
    (11, 2),   -- Food Donation Drive
    (13, 2),   -- Charity Support Program
    (15, 2),   -- Holiday Donation Campaign

    -- Community Service projects
    (1, 3),    -- Community School Renovation
    (2, 3),    -- Community Center Construction
    (3, 3),    -- Rural Road Improvement
    (5, 3),    -- Community Housing Project
    (6, 3),    -- Community Vegetable Garden
    (8, 3),    -- School Garden Project
    (10, 3),   -- Community Tree Planting
    (12, 3),   -- Community Cleanup
    (13, 3),   -- Charity Support Program
    (14, 3),   -- Senior Community Outreach
    (15, 3);   -- Holiday Donation Campaign

SELECT * FROM project_categories
ORDER BY project_id, category_id;

-- Verifying the relationships
SELECT
    pc.project_id,
    sp.title,
    pc.category_id,
    c.category_name
FROM project_categories pc
JOIN service_projects sp
    ON pc.project_id = sp.project_id
JOIN categories c
    ON pc.category_id = c.category_id
ORDER BY pc.project_id, pc.category_id;
