ALTER TABLE organization
ALTER COLUMN email TYPE VARCHAR(100)
USING oemail[1];

-- Inserting statement 
INSERT INTO organizations (name, description, contact_email, logo_filename)
VALUES
('BrightFuture Builders', 'A nonprofit focused on improving community infrastructure through sustainable construction projects.', 'info@brightfuturebuilders.org', 'brightfuture-logo.png'),
('GreenHarvest Growers', 'An urban farming collective promoting food sustainability and education in local neighborhoods.', 'contact@greenharvest.org', 'greenharvest-logo.png'),
('UnityServe Volunteers', 'A volunteer coordination group supporting local charities and service initiatives.', 'hello@unityserve.org', 'unityserve-logo.png');

-- Selecting statement from organization
SELECT * FROM organizations;

SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'organizations';

-- Changing email datatype from array to varchar
ALTER TABLE organizations
ALTER COLUMN contact_email TYPE VARCHAR(255)
USING contact_email::VARCHAR(255);

SELECT column_name, data_type, udt_name
FROM information_schema.columns
WHERE table_name = 'organizations'
ORDER BY ordinal_position;

--Changing logo_filename datatype from array to varchr
ALTER TABLE organizations
ALTER COLUMN logo_filename TYPE VARCHAR(255)
USING logo_filename::VARCHAR(255);

SELECT column_name, data_type, column_default
FROM information_schema.columns
WHERE table_name = 'organizations'
ORDER BY ordinal_position;

--Auto generate organization_id
ALTER TABLE organizations
ALTER COLUMN organization_id
ADD GENERATED BY DEFAULT AS IDENTITY;

