ALTER TABLE organization
ALTER COLUMN email TYPE VARCHAR(100)
USING oemail[1];

-- Inserting statement 
INSERT INTO organizations (name, description, contact_email, logo_filename)
VALUES
('BrightFuture Builders', 'A nonprofit focused on improving community infrastructure through sustainable construction projects.', 'info@brightfuturebuilders.org', 'brightfuture-logo.png'),
('GreenHarvest Growers', 'An urban farming collective promoting food sustainability and education in local neighborhoods.', 'contact@greenharvest.org', 'greenharvest-logo.png'),
('UnityServe Volunteers', 'A volunteer coordination group supporting local charities and service initiatives.', 'hello@unityserve.org', 'unityserve-logo.png');

-- Selecting statement from organization
SELECT * FROM organizations;

SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'organizations';

__ Changing email datatype from array to varc
ALTER TABLE organizations
ALTER COLUMN contact_email TYPE VARCHAR(255)
USING contact_email::VARCHAR(255);


SELECT column_name, data_type, udt_name
FROM information_schema.columns
WHERE table_name = 'organizations'
ORDER BY ordinal_position;

ALTER TABLE organizations
ALTER COLUMN logo_filename TYPE VARCHAR(255)
USING logo_filename::VARCHAR(255);

SELECT column_name, data_type, column_default
FROM information_schema.columns
WHERE table_name = 'organizations'
ORDER BY ordinal_position;

ALTER TABLE organizations
ALTER COLUMN organization_id
ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT * FROM service_projects;

-- Insert into service project
INSERT INTO service_projects
    (organization_id, title, description, location, date)
VALUES
(1, 'Community School Renovation',
 'Renovation of classrooms and improvement of school facilities.',
 'Lagos', '2026-10-05'),

(1, 'Community Center Construction',
 'Construction of a safe community center for local residents.',
 'Ogun', '2026-10-12'),

(1, 'Rural Road Improvement',
 'Improvement of roads connecting local communities.',
 'Ogun', '2026-10-20'),

(1, 'Clean Water Facility',
 'Construction of a sustainable clean water facility.',
 'Oyo', '2026-11-03'),

(1, 'Community Housing Project',
 'Construction support for affordable community housing.',
 'Lagos', '2026-11-15'),

(2, 'Community Vegetable Garden',
 'Development of a vegetable garden for local residents.',
 'Lagos', '2026-10-08'),

(2, 'Urban Farming Workshop',
 'Teaching residents sustainable urban farming methods.',
 'Ogun', '2026-10-18'),

(2, 'School Garden Project',
 'Creating a learning garden for students.',
 'Oyo', '2026-10-28'),

(2, 'Food Sustainability Program',
 'Promoting sustainable food production in the community.',
 'Lagos', '2026-11-07'),

(2, 'Community Tree Planting',
 'Planting fruit and shade trees around community farms.',
 'Ogun', '2026-11-20'),

(3, 'Food Donation Drive',
 'Collecting and distributing food to families in need.',
 'Lagos', '2026-10-10'),

(3, 'Community Cleanup',
 'Organizing volunteers to clean public community spaces.',
 'Ogun', '2026-10-22'),

(3, 'Charity Support Program',
 'Coordinating volunteers to support local charitable organizations.',
 'Lagos', '2026-11-01'),

(3, 'Senior Community Outreach',
 'Organizing volunteers for community outreach activities.',
 'Oyo', '2026-11-12'),

(3, 'Holiday Donation Campaign',
 'Coordinating donations and volunteers for a seasonal community campaign.',
 'Ogun', '2026-11-25');


SELECT * FROM service_projects;]